---
- name: Systeemupdates uitvoeren
  hosts: bookstack
  become: true
  roles:
    - system-update

- name: BookStack installeren via Docker
  hosts: bookstack
  become: true
  roles:
    - bookstack

- name: Host registreren in monitoringsysteem (Netdata)
  hosts: bookstack
  become: true
  roles:
    - monitoring-agent